### ISSUE TITLE
useAuth return result is not reactive

### ISSUE THREAD

**Issue by coldino** [wobsoriano/svelte-instantdb#44]
Tried to use `useAuth` and it just stays on the loading phase forever, despite auth actually working if I query the DB directly. I'm using Svelte 5.

I believe the way the state object is returned and modified in `useAuth` means that the caller will never see a reactive change.

In `useQuery` there are two major differences:
* state is returned using a getter
* fields within the state are modified directly without reassigning the entire object

PS. other that this I've found the library to be solid! Great work.

**Comment by wobsoriano** [comment]
Appreciate you trying it! <3 <3

**Comment by wobsoriano** [comment]
I have an example here if youre interested

https://github.com/wobsoriano/svelte-instantdb/blob/main/src/routes/auth/%2Bpage.svelte
